spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gxtj?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  thymeleaf:
      cache: false
      check-template: false
  redis:
    port: 6379
    host: 127.0.0.1

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: test


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhoulin.concurrency.bean
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      cache-enabled: true               #二级缓存的全局开关
