spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gxtj?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  thymeleaf:
      cache: false
      check-template: false
  redis:
    port: 6379
    host: 127.0.0.1
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    database: 0                       #默认是索引为0的数据库
    password:
    timeout: 0
    sentinel:
      master: mymaster                #哨兵模式
      nodes: 127.0.0.1:26379,127.0.0.1:26381,127.0.0.1:26382

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: test


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhoulin.concurrency.bean
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      cache-enabled: true               #二级缓存的全局开关
